//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_sessions_and_requests
    {
        public int row_id { get; set; }
        public short session_id { get; set; }
        public int request_id { get; set; }
        public int exec_context_id { get; set; }
        public Nullable<short> blocking_session_id { get; set; }
        public Nullable<int> blocking_exec_context_id { get; set; }
        public Nullable<int> scheduler_id { get; set; }
        public string database_name { get; set; }
        public Nullable<int> user_id { get; set; }
        public string task_state { get; set; }
        public string request_status { get; set; }
        public string session_status { get; set; }
        public Nullable<bool> executing_managed_code { get; set; }
        public System.DateTimeOffset login_time { get; set; }
        public bool is_user_process { get; set; }
        public string host_name { get; set; }
        public string program_name { get; set; }
        public string login_name { get; set; }
        public string wait_type { get; set; }
        public string last_wait_type { get; set; }
        public long wait_duration_ms { get; set; }
        public string wait_resource { get; set; }
        public string resource_description { get; set; }
        public Nullable<long> transaction_id { get; set; }
        public int open_transaction_count { get; set; }
        public Nullable<short> transaction_isolation_level { get; set; }
        public Nullable<int> request_cpu_time { get; set; }
        public Nullable<long> request_logical_reads { get; set; }
        public Nullable<long> request_reads { get; set; }
        public Nullable<long> request_writes { get; set; }
        public Nullable<int> request_total_elapsed_time { get; set; }
        public Nullable<System.DateTimeOffset> request_start_time { get; set; }
        public int memory_usage { get; set; }
        public int session_cpu_time { get; set; }
        public long session_reads { get; set; }
        public long session_writes { get; set; }
        public long session_logical_reads { get; set; }
        public int session_total_scheduled_time { get; set; }
        public int session_total_elapsed_time { get; set; }
        public System.DateTimeOffset session_last_request_start_time { get; set; }
        public Nullable<System.DateTimeOffset> session_last_request_end_time { get; set; }
        public Nullable<int> open_resultsets { get; set; }
        public long session_row_count { get; set; }
        public int prev_error { get; set; }
        public Nullable<int> pending_io_count { get; set; }
        public string command { get; set; }
        public byte[] plan_handle { get; set; }
        public byte[] sql_handle { get; set; }
        public Nullable<int> statement_start_offset { get; set; }
        public Nullable<int> statement_end_offset { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public int snapshot_id { get; set; }
        public bool is_blocking { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
