//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int Id { get; set; }
        public string GoodMsg { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string OrderNumber { get; set; }
        public string Remark { get; set; }
        public string OrderImg { get; set; }
        public int CurrentUnitId { get; set; }
        public int PayTypeId { get; set; }
        public int BillTypeId { get; set; }
        public decimal Money { get; set; }
        public byte Type { get; set; }
    
        public virtual BillType BillType { get; set; }
        public virtual CurrentUnit CurrentUnit { get; set; }
        public virtual PayType PayType { get; set; }
    }
}
