//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class computers_internal
    {
        public int id { get; set; }
        public string virtual_server_name { get; set; }
        public string physical_server_name { get; set; }
        public Nullable<int> is_clustered_server { get; set; }
        public Nullable<int> num_processors { get; set; }
        public string cpu_name { get; set; }
        public string cpu_caption { get; set; }
        public string cpu_family { get; set; }
        public string cpu_architecture { get; set; }
        public Nullable<decimal> cpu_max_clock_speed { get; set; }
        public Nullable<decimal> cpu_clock_speed { get; set; }
        public Nullable<decimal> l2_cache_size { get; set; }
        public Nullable<decimal> l3_cache_size { get; set; }
        public Nullable<float> percent_total_cpu_utilization { get; set; }
        public string urn { get; set; }
        public string powershell_path { get; set; }
        public System.DateTimeOffset processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
    }
}
