//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dacs_internal
    {
        public int dac_id { get; set; }
        public string server_instance_name { get; set; }
        public string dac_name { get; set; }
        public string urn { get; set; }
        public string powershell_path { get; set; }
        public string physical_server_name { get; set; }
        public Nullable<System.DateTime> dac_deploy_date { get; set; }
        public string dac_description { get; set; }
        public Nullable<float> dac_percent_total_cpu_utilization { get; set; }
        public System.DateTimeOffset processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
    }
}
