//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class datafiles_internal
    {
        public string urn { get; set; }
        public string powershell_path { get; set; }
        public System.DateTimeOffset processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
        public string server_instance_name { get; set; }
        public string database_name { get; set; }
        public string filegroup_name { get; set; }
        public string parent_urn { get; set; }
        public string physical_server_name { get; set; }
        public string volume_name { get; set; }
        public string volume_device_id { get; set; }
        public Nullable<float> Growth { get; set; }
        public Nullable<short> GrowthType { get; set; }
        public Nullable<float> MaxSize { get; set; }
        public string Name { get; set; }
        public Nullable<float> Size { get; set; }
        public Nullable<float> UsedSpace { get; set; }
        public string FileName { get; set; }
        public Nullable<long> VolumeFreeSpace { get; set; }
    }
}
