//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class databases_internal
    {
        public string urn { get; set; }
        public string powershell_path { get; set; }
        public System.DateTimeOffset processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
        public string server_instance_name { get; set; }
        public string parent_urn { get; set; }
        public string Collation { get; set; }
        public Nullable<short> CompatibilityLevel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> EncryptionEnabled { get; set; }
        public string Name { get; set; }
        public Nullable<short> RecoveryModel { get; set; }
        public Nullable<bool> Trustworthy { get; set; }
        public Nullable<byte> state { get; set; }
    }
}
