//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class disk_usage
    {
        public Nullable<long> dbsize { get; set; }
        public Nullable<long> logsize { get; set; }
        public Nullable<long> ftsize { get; set; }
        public Nullable<long> reservedpages { get; set; }
        public Nullable<long> usedpages { get; set; }
        public Nullable<long> pages { get; set; }
        public string database_name { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public int snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
