//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class io_virtual_file_stats
    {
        public string database_name { get; set; }
        public int database_id { get; set; }
        public string logical_file_name { get; set; }
        public int file_id { get; set; }
        public string type_desc { get; set; }
        public string logical_disk { get; set; }
        public Nullable<long> num_of_reads { get; set; }
        public Nullable<long> num_of_bytes_read { get; set; }
        public Nullable<long> io_stall_read_ms { get; set; }
        public Nullable<long> num_of_writes { get; set; }
        public Nullable<long> num_of_bytes_written { get; set; }
        public Nullable<long> io_stall_write_ms { get; set; }
        public Nullable<long> size_on_disk_bytes { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public int snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
