//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OAEntities : DbContext
    {
        public OAEntities()
            : base("name=OAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<performance_counter_report_group_items> performance_counter_report_group_items { get; set; }
        public DbSet<snapshot_timetable_internal> snapshot_timetable_internal { get; set; }
        public DbSet<snapshots_internal> snapshots_internal { get; set; }
        public DbSet<source_info_internal> source_info_internal { get; set; }
        public DbSet<supported_collector_types_internal> supported_collector_types_internal { get; set; }
        public DbSet<wait_categories> wait_categories { get; set; }
        public DbSet<wait_types> wait_types { get; set; }
        public DbSet<ActionInfo> ActionInfo { get; set; }
        public DbSet<Department> Department { get; set; }
        public DbSet<FileInfo> FileInfo { get; set; }
        public DbSet<OrderInfo> OrderInfo { get; set; }
        public DbSet<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
        public DbSet<RoleInfo> RoleInfo { get; set; }
        public DbSet<WF_Instance> WF_Instance { get; set; }
        public DbSet<WF_StepInfo> WF_StepInfo { get; set; }
        public DbSet<WF_Temp> WF_Temp { get; set; }
        public DbSet<active_sessions_and_requests> active_sessions_and_requests { get; set; }
        public DbSet<disk_usage> disk_usage { get; set; }
        public DbSet<distinct_queries> distinct_queries { get; set; }
        public DbSet<distinct_query_to_handle> distinct_query_to_handle { get; set; }
        public DbSet<io_virtual_file_stats> io_virtual_file_stats { get; set; }
        public DbSet<log_usage> log_usage { get; set; }
        public DbSet<notable_query_plan> notable_query_plan { get; set; }
        public DbSet<notable_query_text> notable_query_text { get; set; }
        public DbSet<os_latch_stats> os_latch_stats { get; set; }
        public DbSet<os_memory_nodes> os_memory_nodes { get; set; }
        public DbSet<os_process_memory> os_process_memory { get; set; }
        public DbSet<os_schedulers> os_schedulers { get; set; }
        public DbSet<os_wait_stats> os_wait_stats { get; set; }
        public DbSet<performance_counter_instances> performance_counter_instances { get; set; }
        public DbSet<performance_counter_values> performance_counter_values { get; set; }
        public DbSet<sql_process_and_system_memory> sql_process_and_system_memory { get; set; }
        public DbSet<sysutility_ucp_cpu_memory_configurations_internal> sysutility_ucp_cpu_memory_configurations_internal { get; set; }
        public DbSet<sysutility_ucp_dac_collected_execution_statistics_internal> sysutility_ucp_dac_collected_execution_statistics_internal { get; set; }
        public DbSet<sysutility_ucp_volumes_internal> sysutility_ucp_volumes_internal { get; set; }
        public DbSet<trace_info> trace_info { get; set; }
        public DbSet<computers_internal> computers_internal { get; set; }
        public DbSet<cpu_utilization_internal> cpu_utilization_internal { get; set; }
        public DbSet<dacs_internal> dacs_internal { get; set; }
        public DbSet<databases_internal> databases_internal { get; set; }
        public DbSet<datafiles_internal> datafiles_internal { get; set; }
        public DbSet<filegroups_internal> filegroups_internal { get; set; }
        public DbSet<logfiles_internal> logfiles_internal { get; set; }
        public DbSet<smo_servers_internal> smo_servers_internal { get; set; }
        public DbSet<space_utilization_internal> space_utilization_internal { get; set; }
        public DbSet<volumes_internal> volumes_internal { get; set; }
        public DbSet<consistent_batch_manifests_internal> consistent_batch_manifests_internal { get; set; }
        public DbSet<purge_info_internal> purge_info_internal { get; set; }
        public DbSet<os_memory_clerks> os_memory_clerks { get; set; }
        public DbSet<query_stats> query_stats { get; set; }
        public DbSet<sysutility_ucp_batch_manifests_internal> sysutility_ucp_batch_manifests_internal { get; set; }
        public DbSet<sysutility_ucp_smo_properties_internal> sysutility_ucp_smo_properties_internal { get; set; }
        public DbSet<trace_data> trace_data { get; set; }
    }
}
