//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class notable_query_plan
    {
        public byte[] sql_handle { get; set; }
        public byte[] plan_handle { get; set; }
        public int statement_start_offset { get; set; }
        public int statement_end_offset { get; set; }
        public long plan_generation_num { get; set; }
        public System.DateTimeOffset creation_time { get; set; }
        public Nullable<short> database_id { get; set; }
        public Nullable<int> object_id { get; set; }
        public string object_name { get; set; }
        public string query_plan { get; set; }
        public int source_id { get; set; }
    
        public virtual source_info_internal source_info_internal { get; set; }
    }
}
