//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_memory_clerks
    {
        public string type { get; set; }
        public Nullable<short> memory_node_id { get; set; }
        public Nullable<long> single_pages_kb { get; set; }
        public Nullable<long> multi_pages_kb { get; set; }
        public Nullable<long> virtual_memory_reserved_kb { get; set; }
        public Nullable<long> virtual_memory_committed_kb { get; set; }
        public Nullable<long> awe_allocated_kb { get; set; }
        public Nullable<long> shared_memory_reserved_kb { get; set; }
        public Nullable<long> shared_memory_committed_kb { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public int snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
