//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_process_memory
    {
        public long physical_memory_in_use_kb { get; set; }
        public long large_page_allocations_kb { get; set; }
        public long locked_page_allocations_kb { get; set; }
        public long total_virtual_address_space_kb { get; set; }
        public long virtual_address_space_reserved_kb { get; set; }
        public long virtual_address_space_committed_kb { get; set; }
        public long virtual_address_space_available_kb { get; set; }
        public long page_fault_count { get; set; }
        public int memory_utilization_percentage { get; set; }
        public long available_commit_limit_kb { get; set; }
        public bool process_physical_memory_low { get; set; }
        public bool process_virtual_memory_low { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public int snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
