//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class os_schedulers
    {
        public int parent_node_id { get; set; }
        public int scheduler_id { get; set; }
        public int cpu_id { get; set; }
        public string status { get; set; }
        public bool is_idle { get; set; }
        public int preemptive_switches_count { get; set; }
        public int context_switches_count { get; set; }
        public int yield_count { get; set; }
        public int current_tasks_count { get; set; }
        public int runnable_tasks_count { get; set; }
        public long work_queue_count { get; set; }
        public int pending_disk_io_count { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public int snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
