//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class performance_counter_values
    {
        public int performance_counter_instance_id { get; set; }
        public int snapshot_id { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public double formatted_value { get; set; }
        public long raw_value_first { get; set; }
        public Nullable<long> raw_value_second { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
