//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class smo_servers_internal
    {
        public string urn { get; set; }
        public string powershell_path { get; set; }
        public System.DateTimeOffset processing_time { get; set; }
        public Nullable<System.DateTimeOffset> batch_time { get; set; }
        public Nullable<short> AuditLevel { get; set; }
        public string BackupDirectory { get; set; }
        public string BrowserServiceAccount { get; set; }
        public Nullable<short> BrowserStartMode { get; set; }
        public string BuildClrVersionString { get; set; }
        public Nullable<int> BuildNumber { get; set; }
        public string Collation { get; set; }
        public Nullable<int> CollationID { get; set; }
        public Nullable<int> ComparisonStyle { get; set; }
        public string ComputerNamePhysicalNetBIOS { get; set; }
        public string DefaultFile { get; set; }
        public string DefaultLog { get; set; }
        public string Edition { get; set; }
        public Nullable<short> EngineEdition { get; set; }
        public string ErrorLogPath { get; set; }
        public string FilestreamShareName { get; set; }
        public string InstallDataDirectory { get; set; }
        public string InstallSharedDirectory { get; set; }
        public string InstanceName { get; set; }
        public Nullable<bool> IsCaseSensitive { get; set; }
        public Nullable<bool> IsClustered { get; set; }
        public Nullable<bool> IsFullTextInstalled { get; set; }
        public Nullable<bool> IsSingleUser { get; set; }
        public string Language { get; set; }
        public string MailProfile { get; set; }
        public string MasterDBLogPath { get; set; }
        public string MasterDBPath { get; set; }
        public Nullable<byte> MaxPrecision { get; set; }
        public string Name { get; set; }
        public Nullable<bool> NamedPipesEnabled { get; set; }
        public string NetName { get; set; }
        public Nullable<int> NumberOfLogFiles { get; set; }
        public string OSVersion { get; set; }
        public Nullable<short> PerfMonMode { get; set; }
        public Nullable<int> PhysicalMemory { get; set; }
        public string Platform { get; set; }
        public Nullable<short> Processors { get; set; }
        public Nullable<int> ProcessorUsage { get; set; }
        public string Product { get; set; }
        public string ProductLevel { get; set; }
        public string ResourceVersionString { get; set; }
        public string RootDirectory { get; set; }
        public Nullable<short> ServerType { get; set; }
        public string ServiceAccount { get; set; }
        public string ServiceInstanceId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<short> ServiceStartMode { get; set; }
        public Nullable<short> SqlCharSet { get; set; }
        public string SqlCharSetName { get; set; }
        public string SqlDomainGroup { get; set; }
        public Nullable<short> SqlSortOrder { get; set; }
        public string SqlSortOrderName { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> TapeLoadWaitTime { get; set; }
        public Nullable<bool> TcpEnabled { get; set; }
        public Nullable<int> VersionMajor { get; set; }
        public Nullable<int> VersionMinor { get; set; }
        public string VersionString { get; set; }
    }
}
