//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class snapshots_internal
    {
        public snapshots_internal()
        {
            this.active_sessions_and_requests = new HashSet<active_sessions_and_requests>();
            this.sysutility_ucp_dac_collected_execution_statistics_internal = new HashSet<sysutility_ucp_dac_collected_execution_statistics_internal>();
            this.disk_usage = new HashSet<disk_usage>();
            this.io_virtual_file_stats = new HashSet<io_virtual_file_stats>();
            this.log_usage = new HashSet<log_usage>();
            this.os_latch_stats = new HashSet<os_latch_stats>();
            this.os_memory_clerks = new HashSet<os_memory_clerks>();
            this.os_memory_nodes = new HashSet<os_memory_nodes>();
            this.os_process_memory = new HashSet<os_process_memory>();
            this.os_schedulers = new HashSet<os_schedulers>();
            this.os_wait_stats = new HashSet<os_wait_stats>();
            this.performance_counter_values = new HashSet<performance_counter_values>();
            this.query_stats = new HashSet<query_stats>();
            this.sql_process_and_system_memory = new HashSet<sql_process_and_system_memory>();
            this.sysutility_ucp_cpu_memory_configurations_internal = new HashSet<sysutility_ucp_cpu_memory_configurations_internal>();
            this.sysutility_ucp_batch_manifests_internal = new HashSet<sysutility_ucp_batch_manifests_internal>();
            this.sysutility_ucp_smo_properties_internal = new HashSet<sysutility_ucp_smo_properties_internal>();
            this.trace_data = new HashSet<trace_data>();
            this.trace_info = new HashSet<trace_info>();
            this.sysutility_ucp_volumes_internal = new HashSet<sysutility_ucp_volumes_internal>();
        }
    
        public int snapshot_id { get; set; }
        public int snapshot_time_id { get; set; }
        public int source_id { get; set; }
        public long log_id { get; set; }
    
        public virtual snapshot_timetable_internal snapshot_timetable_internal { get; set; }
        public virtual ICollection<active_sessions_and_requests> active_sessions_and_requests { get; set; }
        public virtual ICollection<sysutility_ucp_dac_collected_execution_statistics_internal> sysutility_ucp_dac_collected_execution_statistics_internal { get; set; }
        public virtual ICollection<disk_usage> disk_usage { get; set; }
        public virtual ICollection<io_virtual_file_stats> io_virtual_file_stats { get; set; }
        public virtual ICollection<log_usage> log_usage { get; set; }
        public virtual ICollection<os_latch_stats> os_latch_stats { get; set; }
        public virtual ICollection<os_memory_clerks> os_memory_clerks { get; set; }
        public virtual ICollection<os_memory_nodes> os_memory_nodes { get; set; }
        public virtual ICollection<os_process_memory> os_process_memory { get; set; }
        public virtual ICollection<os_schedulers> os_schedulers { get; set; }
        public virtual ICollection<os_wait_stats> os_wait_stats { get; set; }
        public virtual ICollection<performance_counter_values> performance_counter_values { get; set; }
        public virtual ICollection<query_stats> query_stats { get; set; }
        public virtual source_info_internal source_info_internal { get; set; }
        public virtual ICollection<sql_process_and_system_memory> sql_process_and_system_memory { get; set; }
        public virtual ICollection<sysutility_ucp_cpu_memory_configurations_internal> sysutility_ucp_cpu_memory_configurations_internal { get; set; }
        public virtual ICollection<sysutility_ucp_batch_manifests_internal> sysutility_ucp_batch_manifests_internal { get; set; }
        public virtual ICollection<sysutility_ucp_smo_properties_internal> sysutility_ucp_smo_properties_internal { get; set; }
        public virtual ICollection<trace_data> trace_data { get; set; }
        public virtual ICollection<trace_info> trace_info { get; set; }
        public virtual ICollection<sysutility_ucp_volumes_internal> sysutility_ucp_volumes_internal { get; set; }
    }
}
