//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class snapshot_timetable_internal
    {
        public snapshot_timetable_internal()
        {
            this.snapshots_internal = new HashSet<snapshots_internal>();
        }
    
        public int snapshot_time_id { get; set; }
        public System.DateTimeOffset snapshot_time { get; set; }
    
        public virtual ICollection<snapshots_internal> snapshots_internal { get; set; }
    }
}
