//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class source_info_internal
    {
        public source_info_internal()
        {
            this.snapshots_internal = new HashSet<snapshots_internal>();
            this.distinct_queries = new HashSet<distinct_queries>();
            this.distinct_query_to_handle = new HashSet<distinct_query_to_handle>();
            this.notable_query_plan = new HashSet<notable_query_plan>();
            this.notable_query_text = new HashSet<notable_query_text>();
            this.trace_info = new HashSet<trace_info>();
        }
    
        public int source_id { get; set; }
        public System.Guid collection_set_uid { get; set; }
        public string instance_name { get; set; }
        public short days_until_expiration { get; set; }
        public string @operator { get; set; }
    
        public virtual ICollection<snapshots_internal> snapshots_internal { get; set; }
        public virtual ICollection<distinct_queries> distinct_queries { get; set; }
        public virtual ICollection<distinct_query_to_handle> distinct_query_to_handle { get; set; }
        public virtual ICollection<notable_query_plan> notable_query_plan { get; set; }
        public virtual ICollection<notable_query_text> notable_query_text { get; set; }
        public virtual ICollection<trace_info> trace_info { get; set; }
    }
}
