//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class space_utilization_internal
    {
        public System.DateTimeOffset processing_time { get; set; }
        public byte aggregation_type { get; set; }
        public byte object_type { get; set; }
        public string virtual_server_name { get; set; }
        public string server_instance_name { get; set; }
        public string volume_device_id { get; set; }
        public string database_name { get; set; }
        public string filegroup_name { get; set; }
        public string dbfile_name { get; set; }
        public Nullable<float> used_space_bytes { get; set; }
        public Nullable<float> allocated_space_bytes { get; set; }
        public Nullable<float> total_space_bytes { get; set; }
        public Nullable<float> available_space_bytes { get; set; }
    }
}
