//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sql_process_and_system_memory
    {
        public long sql_physical_memory_in_use_kb { get; set; }
        public long sql_large_page_allocations_kb { get; set; }
        public long sql_locked_page_allocations_kb { get; set; }
        public long sql_total_virtual_address_space_kb { get; set; }
        public long sql_virtual_address_space_reserved_kb { get; set; }
        public long sql_virtual_address_space_committed_kb { get; set; }
        public long sql_virtual_address_space_available_kb { get; set; }
        public long sql_page_fault_count { get; set; }
        public int sql_memory_utilization_percentage { get; set; }
        public long sql_available_commit_limit_kb { get; set; }
        public bool sql_process_physical_memory_low { get; set; }
        public bool sql_process_virtual_memory_low { get; set; }
        public long system_total_physical_memory_kb { get; set; }
        public long system_available_physical_memory_kb { get; set; }
        public long system_total_page_file_kb { get; set; }
        public long system_available_page_file_kb { get; set; }
        public long system_cache_kb { get; set; }
        public long system_kernel_paged_pool_kb { get; set; }
        public long system_kernel_nonpaged_pool_kb { get; set; }
        public bool system_high_memory_signal_state { get; set; }
        public bool system_low_memory_signal_state { get; set; }
        public long bpool_commit_target { get; set; }
        public long bpool_committed { get; set; }
        public long bpool_visible { get; set; }
        public System.DateTimeOffset collection_time { get; set; }
        public int snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
