//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_dac_collected_execution_statistics_internal
    {
        public string physical_server_name { get; set; }
        public string server_instance_name { get; set; }
        public string dac_db { get; set; }
        public Nullable<System.DateTime> dac_deploy_date { get; set; }
        public string dac_description { get; set; }
        public string dac_name { get; set; }
        public Nullable<System.DateTimeOffset> interval_start_time { get; set; }
        public Nullable<System.DateTimeOffset> interval_end_time { get; set; }
        public Nullable<long> interval_cpu_time_ms { get; set; }
        public Nullable<float> interval_cpu_pct { get; set; }
        public Nullable<long> lifetime_cpu_time_ms { get; set; }
        public System.DateTimeOffset batch_time { get; set; }
        public Nullable<System.DateTimeOffset> collection_time { get; set; }
        public Nullable<int> snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
