//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_volumes_internal
    {
        public string server_instance_name { get; set; }
        public string virtual_server_name { get; set; }
        public string physical_server_name { get; set; }
        public string volume_device_id { get; set; }
        public string volume_name { get; set; }
        public Nullable<float> total_space_available { get; set; }
        public Nullable<float> free_space { get; set; }
        public System.DateTimeOffset batch_time { get; set; }
        public Nullable<System.DateTimeOffset> collection_time { get; set; }
        public Nullable<int> snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
