//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysutility_ucp_cpu_memory_configurations_internal
    {
        public string server_instance_name { get; set; }
        public Nullable<short> is_clustered_server { get; set; }
        public string virtual_server_name { get; set; }
        public string physical_server_name { get; set; }
        public Nullable<int> num_processors { get; set; }
        public Nullable<float> server_processor_usage { get; set; }
        public Nullable<float> instance_processor_usage { get; set; }
        public string cpu_name { get; set; }
        public string cpu_caption { get; set; }
        public string cpu_family { get; set; }
        public string cpu_architecture { get; set; }
        public Nullable<decimal> cpu_max_clock_speed { get; set; }
        public Nullable<decimal> cpu_clock_speed { get; set; }
        public Nullable<decimal> l2_cache_size { get; set; }
        public Nullable<decimal> l3_cache_size { get; set; }
        public System.DateTimeOffset batch_time { get; set; }
        public Nullable<System.DateTimeOffset> collection_time { get; set; }
        public Nullable<int> snapshot_id { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
    }
}
