//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class trace_data
    {
        public int trace_info_id { get; set; }
        public int snapshot_id { get; set; }
        public string TextData { get; set; }
        public byte[] BinaryData { get; set; }
        public Nullable<int> DatabaseID { get; set; }
        public Nullable<long> TransactionID { get; set; }
        public Nullable<int> LineNumber { get; set; }
        public string NTUserName { get; set; }
        public string NTDomainName { get; set; }
        public string HostName { get; set; }
        public Nullable<int> ClientProcessID { get; set; }
        public string ApplicationName { get; set; }
        public string LoginName { get; set; }
        public Nullable<int> SPID { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<System.DateTimeOffset> StartTime { get; set; }
        public Nullable<System.DateTimeOffset> EndTime { get; set; }
        public Nullable<long> Reads { get; set; }
        public Nullable<long> Writes { get; set; }
        public Nullable<int> CPU { get; set; }
        public Nullable<long> Permissions { get; set; }
        public Nullable<int> Severity { get; set; }
        public Nullable<int> EventSubClass { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public Nullable<int> Success { get; set; }
        public Nullable<int> IndexID { get; set; }
        public Nullable<int> IntegerData { get; set; }
        public string ServerName { get; set; }
        public Nullable<int> EventClass { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> NestLevel { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Error { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> Handle { get; set; }
        public string ObjectName { get; set; }
        public string DatabaseName { get; set; }
        public string FileName { get; set; }
        public string OwnerName { get; set; }
        public string RoleName { get; set; }
        public string TargetUserName { get; set; }
        public string DBUserName { get; set; }
        public byte[] LoginSid { get; set; }
        public string TargetLoginName { get; set; }
        public byte[] TargetLoginSid { get; set; }
        public Nullable<int> ColumnPermissions { get; set; }
        public string LinkedServerName { get; set; }
        public string ProviderName { get; set; }
        public string MethodName { get; set; }
        public Nullable<long> RowCounts { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<long> XactSequence { get; set; }
        public long EventSequence { get; set; }
        public Nullable<long> BigintData1 { get; set; }
        public Nullable<long> BigintData2 { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<int> IntegerData2 { get; set; }
        public Nullable<long> ObjectID2 { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string ParentName { get; set; }
        public Nullable<int> IsSystem { get; set; }
        public Nullable<int> Offset { get; set; }
        public Nullable<int> SourceDatabaseID { get; set; }
        public byte[] SqlHandle { get; set; }
        public string SessionLoginName { get; set; }
        public byte[] PlanHandle { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual snapshots_internal snapshots_internal { get; set; }
        public virtual trace_info trace_info { get; set; }
    }
}
