//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebApp.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wait_categories
    {
        public wait_categories()
        {
            this.wait_types = new HashSet<wait_types>();
        }
    
        public short category_id { get; set; }
        public string category_name { get; set; }
        public bool ignore { get; set; }
    
        public virtual ICollection<wait_types> wait_types { get; set; }
    }
}
